proc-chance:
  fortune: 0.1
  explosive: 0.1
  meteor: 0.1
  flow: 0.1
  lightning: 0.1

block-xp:
  # Ores
  COAL_ORE: 1.25
  COPPER_ORE: 1.25
  IRON_ORE: 1.5
  GOLD_ORE: 1.5
  DIAMOND_ORE: 2.0
  EMERALD_ORE: 3.0
  REDSTONE_ORE: 1.5
  LAPIS_ORE: 1.5
  NETHER_QUARTZ_ORE: 1.0
  NETHER_GOLD_ORE: 1.0
  # Special
  OBSIDIAN: 1.25
  ANCIENT_DEBRIS: 4.0

level-xp:
  # Mining
  1: 100
  2: 200
  3: 300
  4: 400
  5: 500
